version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python3 -m pip install --user -r requirements.txt
      - run: python3 -m test
      
