version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run: pip install -r requirements.txt
workflows:
  build tests:
    jobs:
      - run_tests