version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            pip install -r requirements.txt