version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run: 
        name: Install Python Dependencies
        command: |
          pip install -r requirements.txt
workflows:
  build tests:
    jobs:
      - run_tests